const views = ['ask','sources','policies','audit','team','settings'];
const navItems = document.querySelectorAll('.nav-item');
const pageName = document.getElementById('page-name');
const names = {ask:'Ask Nexus',sources:'Source library',policies:'Access policies',audit:'Audit trail',team:'Team & roles',settings:'Settings'};
function showView(view){views.forEach(v=>document.getElementById(`${v}-view`).classList.toggle('active-view',v===view));navItems.forEach(n=>n.classList.toggle('active',n.dataset.view===view));pageName.textContent=names[view]||'Ask Nexus';window.scrollTo({top:0,behavior:'smooth'})}
navItems.forEach(item=>item.addEventListener('click',()=>showView(item.dataset.view)));
document.querySelectorAll('[data-view]').forEach(item=>{if(!item.classList.contains('nav-item'))item.addEventListener('click',()=>showView(item.dataset.view))});
const roleButton=document.getElementById('role-button'), roleMenu=document.getElementById('role-menu'), roleName=document.getElementById('role-name');
roleButton.addEventListener('click',()=>roleMenu.classList.toggle('open'));
const roleLabels={admin:'Amara · Admin',engineering:'Leo · Engineering',finance:'Mina · Finance',people:'Jules · People ops'};
document.querySelectorAll('[data-role]').forEach(btn=>btn.addEventListener('click',()=>{roleName.textContent=roleLabels[btn.dataset.role];roleMenu.classList.remove('open');showToast(`Viewing permissions as ${roleLabels[btn.dataset.role]}`)}));
document.addEventListener('click',e=>{if(!e.target.closest('.role-control'))roleMenu.classList.remove('open')});
const input=document.getElementById('query-input'), answerArea=document.getElementById('answer-area'), askButton=document.getElementById('ask-button');
const questions={
 'What changed in the FY26 hiring plan?':{title:'FY26 hiring plan: three changes to know',copy:'The plan moves 12 roles from Q2 to Q3, adds a dedicated security hiring pod, and holds non-critical backfills until the operating review. The updated plan is owned by People Ops and Finance.',docs:['FY26 operating plan · v3','Hiring plan notes · Sep 24','Operating review agenda']},
 'Summarize the vendor renewal risks':{title:'Vendor renewal risks are concentrated in two contracts',copy:'Two renewals carry material risk: Atlas Cloud has a 14% proposed increase, while Relay Support has an unresolved data-processing addendum. Both are flagged for legal review before October 15.',docs:['Vendor renewal register','Atlas Cloud MSA · redlines','Legal intake · 2026-091']},
 'How do we handle incident severity?':{title:'Incident severity is assigned by impact, not by team',copy:'Use customer impact, data exposure, and recovery time to assign a level. SEV-1 requires the incident commander to page the executive channel immediately; SEV-2 stays within the service team until escalation criteria are met.',docs:['Incident response handbook','Severity rubric · v2','On-call escalation policy']}
};
function ask(){const value=input.value.trim();if(!value){input.focus();return}const match=questions[value]||{title:'Here is what I found for your question',copy:`I searched the collections available to your current role for “${value}”. The strongest matches point to an active policy and two recent source documents. Open a citation to verify the underlying language.`,docs:['Knowledge base search results','Access policy snapshot','Recent source update']};answerArea.innerHTML=`<div class="answer-header"><div><div class="answer-label"><span class="spark">✦</span> Nexus answer <span class="live-pill">GROUNDED</span></div><h2>${match.title}</h2></div><div class="answer-meta">${match.docs.length} sources · 0 restricted <span class="sync-dot"></span></div></div><div class="result-grid"><div class="result-copy"><p>${match.copy}</p><div class="result-actions"><button class="citation-button">View reasoning trail ↗</button><button class="citation-button muted">Copy answer</button></div></div><div class="evidence"><div class="evidence-title">Evidence trail <span>TOP MATCHES</span></div>${match.docs.map((doc,i)=>`<div class="evidence-row"><span class="doc-num">0${i+1}</span><span>${doc}</span><span class="score">${98-i*5}%</span></div>`).join('')}</div></div>`;answerArea.classList.add('answer-result');showToast('Answer grounded in permission-aware sources')}
askButton.addEventListener('click',ask);input.addEventListener('keydown',e=>{if(e.key==='Enter')ask()});document.querySelectorAll('.suggestion').forEach(btn=>btn.addEventListener('click',()=>{input.value=btn.textContent;ask()}));
async function copyAnswer(){const answer=answerArea.querySelector('.result-copy p')?.textContent;if(!answer)return;try{await navigator.clipboard.writeText(answer);showToast('Answer copied to clipboard')}catch{const textarea=document.createElement('textarea');textarea.value=answer;textarea.setAttribute('readonly','');textarea.style.position='fixed';textarea.style.opacity='0';document.body.append(textarea);textarea.select();const copied=document.execCommand('copy');textarea.remove();showToast(copied?'Answer copied to clipboard':'Unable to copy answer')}}
document.addEventListener('click',async e=>{const button=e.target.closest('.citation-button');if(!button)return;if(button.classList.contains('muted'))await copyAnswer();else showToast('Reasoning trail opened')});
document.querySelectorAll('.toggle').forEach(toggle=>toggle.addEventListener('click',()=>{toggle.classList.toggle('on');showToast(toggle.classList.contains('on')?'Setting enabled':'Setting disabled')}));
function showToast(message){const toast=document.getElementById('toast');toast.textContent=message;toast.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>toast.classList.remove('show'),2600)}
